In [ ]:
import numpy as np

In [ ]:
a = np.array(['vaibhav','solanke'])

In [ ]:
b = np.array(['sweetiee','sweet'])

In [ ]:
a>b

array([ True, False])

In [ ]:
a>b.help

AttributeError: 'numpy.ndarray' object has no attribute 'help'

In [ ]:
help(np.greater)

Help on ufunc:

greater = <ufunc 'greater'>
    greater(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Return the truth value of (x1 > x2) element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        Input arrays.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``out=None``, locations within it where the condition is False will
        remain uninitialized.
    **kwargs
        For other keyword-only arguments, see the
        :ref:`ufunc docs <ufuncs.kwargs>`.

    Returns
    -------
    out : ndarray or scalar
        Output array, element-wise comparison of `x1` and `x2`.
        Typically of type bool, unless ``dtype=object`` is passed.
        This is a scalar if both `x1` and `x2` are scalars.


    See Also
    --------
    greater_equal, less, less_equal, equal, not_equal

    Examples
    --------
    >>> np.greater([4,2],[2,2])
    array([ True, False])

    The ``>`` operator can be used as a shorthand for ``np.greater`` on
    ndarrays.

    >>> a = np.array([4, 2])
    >>> b = np.array([2, 2])
    >>> a > b
    array([ True, False])

In [ ]:
a = np.array([[6, 6 ,4 ,7, 9],
 [0, 2, 2, 9, 3],
 [6, 0, 2, 5, 2],
 [2, 4, 3, 5, 5]])

In [ ]:
a.shape

(4, 5)

In [ ]:
a.ndim

2

In [ ]:
a = np.array([8,1,10,2,3,7,4,5,6,7])

In [ ]:
a.argsort()

array([1, 3, 4, 6, 7, 8, 5, 9, 0, 2])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([0 for i in range(a.shape[0])]).reshape(a.shape[0],1)
c =np.hstack((b,a,b))
d = np.array([0 for i in range(c.shape[1])])
e = np.vstack((d,c,d))
e

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

In [ ]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
num_splits = 4
a = np.split(data,num_splits,axis = 0)
b = a[-1:]+a[:-1]
d = np.concatenate(b)
d

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
pd.read

In [ ]:
foo = 'mppmmt'
result=''.join(dict.fromkeys(foo))
result

'mpt'

In [ ]:
s = 'aAsSdDfF'

In [ ]:
set(s)

{'A', 'D', 'F', 'S', 'a', 'd', 'f', 's'}

In [ ]:
s.lower()

'aassddff'

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('sales_customer_segmentation.csv')

In [3]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
375182,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
375183,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
375184,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
375185,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
375186,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375187 entries, 0 to 375186
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    375187 non-null  int64
 1   StockCode    375187 non-null  object
 2   Description  375187 non-null  object
 3   Quantity     375187 non-null  int64
 4   InvoiceDate  375187 non-null  object
 5   UnitPrice    375187 non-null  float64
 6   CustomerID   375187 non-null  float64
 7   Country      375187 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 22.9+ MB

In [5]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375187 entries, 0 to 375186
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    375187 non-null  int64
 1   StockCode    375187 non-null  object
 2   Description  375187 non-null  object
 3   Quantity     375187 non-null  int64
 4   InvoiceDate  375187 non-null  datetime64[ns]
 5   UnitPrice    375187 non-null  float64
 6   CustomerID   375187 non-null  float64
 7   Country      375187 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 22.9+ MB

In [7]:
data = df.copy()

In [8]:
data['Amount']=data['Quantity']*data['UnitPrice']

In [ ]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
375182,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
375183,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
375184,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
375185,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
375186,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [16]:
def total(x):
  x['Total']=x['Amount'].sum()
  return x

In [18]:
Data=data.groupby('InvoiceNo').apply(total)

<ipython-input-18-4970ab05b4c7>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  Data=data.groupby('InvoiceNo').apply(total)

In [20]:
Data

                  InvoiceNo StockCode                          Description  \
InvoiceNo
536365    0          536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
          1          536365     71053                  WHITE METAL LANTERN
          2          536365    84406B       CREAM CUPID HEARTS COAT HANGER
          3          536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
          4          536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...                     ...       ...                                  ...
581587    375182     581587     22613          PACK OF 20 SPACEBOY NAPKINS
          375183     581587     22899         CHILDREN'S APRON DOLLY GIRL
          375184     581587     23254        CHILDRENS CUTLERY DOLLY GIRL
          375185     581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
          375186     581587     22138        BAKING SET 9 PIECE RETROSPOT

                  Quantity         InvoiceDate  UnitPrice  CustomerID  \
InvoiceNo
536365    0              6 2010-12-01 08:26:00       2.55     17850.0
          1              6 2010-12-01 08:26:00       3.39     17850.0
          2              8 2010-12-01 08:26:00       2.75     17850.0
          3              6 2010-12-01 08:26:00       3.39     17850.0
          4              6 2010-12-01 08:26:00       3.39     17850.0
...                    ...                 ...        ...         ...
581587    375182        12 2011-12-09 12:50:00       0.85     12680.0
          375183         6 2011-12-09 12:50:00       2.10     12680.0
          375184         4 2011-12-09 12:50:00       4.15     12680.0
          375185         4 2011-12-09 12:50:00       4.15     12680.0
          375186         3 2011-12-09 12:50:00       4.95     12680.0

                         Country  Amount   Total
InvoiceNo
536365    0       United Kingdom   15.30  139.12
          1       United Kingdom   20.34  139.12
          2       United Kingdom   22.00  139.12
          3       United Kingdom   20.34  139.12
          4       United Kingdom   20.34  139.12
...                          ...     ...     ...
581587    375182          France   10.20  249.45
          375183          France   12.60  249.45
          375184          France   16.60  249.45
          375185          France   16.60  249.45
          375186          France   14.85  249.45

[375187 rows x 10 columns]

In [21]:
Data.reset_index(drop=True,inplace=True)

In [22]:
Data.head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,139.12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,139.12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,139.12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,139.12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,139.12
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,15.30,139.12
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,25.50,139.12
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10,22.20
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10,22.20
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,54.08,258.83
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,12.60,258.83
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,12.60,258.83
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom,30.00,258.83
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom,9.90,258.83
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,25.50,258.83
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,14.85,258.83
16,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,17.85,258.83
17,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,17.85,258.83
18,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,31.80,258.83
19,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,31.80,258.83
20,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,25.50,70.05
21,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,14.85,70.05
22,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,14.85,70.05
23,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,14.85,70.05
24,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom,17.85,17.85
25,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,90.00,801.86
26,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,90.00,801.86
27,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,45.00,801.86
28,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France,10.20,801.86
29,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France,15.60,801.86

In [23]:
def func(x):
  x['last_purchase_date']=x['InvoiceDate'].max()
  x['first_purchase_date']=x['InvoiceDate'].min()
  x['num_purchases']=x['InvoiceNo'].nunique()
  x['monetary']=x['Total'].sum()
  return x

In [24]:
New_data=Data.groupby('CustomerID',group_keys=False).apply(func)

<ipython-input-24-24e5485781e5>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  New_data=Data.groupby('CustomerID',group_keys=False).apply(func)

In [ ]:
New_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,monetary
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,139.12,2010-12-02 15:27:00,2010-12-01 08:26:00,34,69018.88
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,139.12,2010-12-02 15:27:00,2010-12-01 08:26:00,34,69018.88
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,139.12,2010-12-02 15:27:00,2010-12-01 08:26:00,34,69018.88
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,139.12,2010-12-02 15:27:00,2010-12-01 08:26:00,34,69018.88
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,139.12,2010-12-02 15:27:00,2010-12-01 08:26:00,34,69018.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,249.45,2011-12-09 12:50:00,2011-08-18 15:44:00,4,10467.65
375183,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,249.45,2011-12-09 12:50:00,2011-08-18 15:44:00,4,10467.65
375184,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,249.45,2011-12-09 12:50:00,2011-08-18 15:44:00,4,10467.65
375185,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,249.45,2011-12-09 12:50:00,2011-08-18 15:44:00,4,10467.65
375186,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,249.45,2011-12-09 12:50:00,2011-08-18 15:44:00,4,10467.65

In [25]:
New_data[New_data['CustomerID']==12347.0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,monetary
9890,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
9891,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
9892,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
9893,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
9894,537626,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12,2010-12-07 14:57:00,1.25,12347.0,Iceland,15.00,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371900,581180,20719,WOODLAND CHARLOTTE BAG,10,2011-12-07 15:52:00,0.85,12347.0,Iceland,8.50,224.82,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
371901,581180,21265,PINK GOOSE FEATHER TREE 60CM,12,2011-12-07 15:52:00,1.95,12347.0,Iceland,23.40,224.82,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
371902,581180,23271,CHRISTMAS TABLE SILVER CANDLE SPIKE,16,2011-12-07 15:52:00,0.83,12347.0,Iceland,13.28,224.82,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
371903,581180,23506,MINI PLAYING CARDS SPACEBOY,20,2011-12-07 15:52:00,0.42,12347.0,Iceland,8.40,224.82,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23
371904,581180,23508,MINI PLAYING CARDS DOLLY GIRL,20,2011-12-07 15:52:00,0.42,12347.0,Iceland,8.40,224.82,2011-12-07 15:52:00,2010-12-07 14:57:00,7,122083.23

In [ ]:
1287*66

84942

In [26]:
new_data['last_purchase_date']=new_data['last_purchase_date'].dt.date
new_data['first_purchase_date']=new_data['first_purchase_date'].dt.date
new_data

NameError: name 'new_data' is not defined

In [29]:
New_data['cust_total']=New_data['Quantity']*New_data['UnitPrice']

In [30]:
def cust_tot(x):
  x['ttl']=x['cust_total'].sum()
  return x

In [31]:
NEW_DATA=New_data.groupby('CustomerID').apply(cust_tot)

<ipython-input-31-1694acee6fb8>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  NEW_DATA=New_data.groupby('CustomerID').apply(cust_tot)

In [ ]:
NEW_DATA

                   InvoiceNo StockCode                          Description  \
CustomerID
12346.0    34769      541431     23166       MEDIUM CERAMIC TOP STORAGE JAR
12347.0    9890       537626     85116      BLACK CANDELABRA T-LIGHT HOLDER
           9891       537626     22375    AIRLINE BAG VINTAGE JET SET BROWN
           9892       537626     71477    COLOUR GLASS. STAR T-LIGHT HOLDER
           9893       537626     22492              MINI PAINT SET VINTAGE
...                      ...       ...                                  ...
18287.0    267342     570715     22419                     LIPSTICK PEN RED
           267343     570715     22866        HAND WARMER SCOTTY DOG DESIGN
           291570     573167     23264   SET OF 3 WOODEN SLEIGH DECORATIONS
           291571     573167     21824  PAINTED METAL STAR WITH HOLLY BELLS
           291572     573167     21014        SWISS CHALET TREE DECORATION

                   Quantity         InvoiceDate  UnitPrice  CustomerID  \
CustomerID
12346.0    34769      74215 2011-01-18 10:01:00       1.04     12346.0
12347.0    9890          12 2010-12-07 14:57:00       2.10     12347.0
           9891           4 2010-12-07 14:57:00       4.25     12347.0
           9892          12 2010-12-07 14:57:00       3.25     12347.0
           9893          36 2010-12-07 14:57:00       0.65     12347.0
...                     ...                 ...        ...         ...
18287.0    267342        12 2011-10-12 10:23:00       0.42     18287.0
           267343        12 2011-10-12 10:23:00       2.10     18287.0
           291570        36 2011-10-28 09:29:00       1.25     18287.0
           291571        48 2011-10-28 09:29:00       0.39     18287.0
           291572        24 2011-10-28 09:29:00       0.29     18287.0

                          Country    Amount     Total  last_purchase_date  \
CustomerID
12346.0    34769   United Kingdom  77183.60  77183.60 2011-01-18 10:01:00
12347.0    9890           Iceland     25.20    711.79 2011-12-07 15:52:00
           9891           Iceland     17.00    711.79 2011-12-07 15:52:00
           9892           Iceland     39.00    711.79 2011-12-07 15:52:00
           9893           Iceland     23.40    711.79 2011-12-07 15:52:00
...                           ...       ...       ...                 ...
18287.0    267342  United Kingdom      5.04   1001.32 2011-10-28 09:29:00
           267343  United Kingdom     25.20   1001.32 2011-10-28 09:29:00
           291570  United Kingdom     45.00     70.68 2011-10-28 09:29:00
           291571  United Kingdom     18.72     70.68 2011-10-28 09:29:00
           291572  United Kingdom      6.96     70.68 2011-10-28 09:29:00

                  first_purchase_date  num_purchases   monetary  cust_total  \
CustomerID
12346.0    34769  2011-01-18 10:01:00              1   77183.60    77183.60
12347.0    9890   2010-12-07 14:57:00              7  122083.23       25.20
           9891   2010-12-07 14:57:00              7  122083.23       17.00
           9892   2010-12-07 14:57:00              7  122083.23       39.00
           9893   2010-12-07 14:57:00              7  122083.23       23.40
...                               ...            ...        ...         ...
18287.0    267342 2011-05-22 10:39:00              3   58738.04        5.04
           267343 2011-05-22 10:39:00              3   58738.04       25.20
           291570 2011-05-22 10:39:00              3   58738.04       45.00
           291571 2011-05-22 10:39:00              3   58738.04       18.72
           291572 2011-05-22 10:39:00              3   58738.04        6.96

                        ttl
CustomerID
12346.0    34769   77183.60
12347.0    9890     4078.95
           9891     4078.95
           9892     4078.95
           9893     4078.95
...                     ...
18287.0    267342   1803.28
           267343   1803.28
           291570   1803.28
           291571   1803.28
           291572   1803.28

[375187 rows x 16 columns]

In [32]:
NEW_DATA[NEW_DATA['CustomerID']==12355.0]

                   InvoiceNo StockCode                         Description  \
CustomerID
12355.0    116213     552449     22693  GROW A FLYTRAP OR SUNFLOWER IN TIN
           116214     552449     23076          ICE CREAM SUNDAE LIP GLOSS
           116215     552449     23077                 DOUGHNUT LIP GLOSS
           116216     552449     22649        STRAWBERRY FAIRY CAKE TEAPOT
           116217     552449    85040A     S/4 PINK FLOWER CANDLES IN BOWL
           116218     552449     22699    ROSES REGENCY TEACUP AND SAUCER
           116219     552449     22697     GREEN REGENCY TEACUP AND SAUCER
           116220     552449     22698      PINK REGENCY TEACUP AND SAUCER
           116221     552449    72802A   ROSE SCENT CANDLE IN JEWELLED BOX
           116222     552449    72802B  OCEAN SCENT CANDLE IN JEWELLED BOX
           116223     552449    72802C   VANILLA SCENT CANDLE JEWELLED BOX

                   Quantity         InvoiceDate  UnitPrice  CustomerID  \
CustomerID
12355.0    116213        24 2011-05-09 13:49:00       1.25     12355.0
           116214        96 2011-05-09 13:49:00       1.25     12355.0
           116215        60 2011-05-09 13:49:00       1.25     12355.0
           116216         8 2011-05-09 13:49:00       4.95     12355.0
           116217        12 2011-05-09 13:49:00       1.65     12355.0
           116218         6 2011-05-09 13:49:00       2.95     12355.0
           116219         6 2011-05-09 13:49:00       2.95     12355.0
           116220         6 2011-05-09 13:49:00       2.95     12355.0
           116221         6 2011-05-09 13:49:00       4.25     12355.0
           116222         6 2011-05-09 13:49:00       4.25     12355.0
           116223         6 2011-05-09 13:49:00       4.25     12355.0

                   Country  Amount  Total  last_purchase_date  \
CustomerID
12355.0    116213  Bahrain    30.0  414.0 2011-05-09 13:49:00
           116214  Bahrain   120.0  414.0 2011-05-09 13:49:00
           116215  Bahrain    75.0  414.0 2011-05-09 13:49:00
           116216  Bahrain    39.6  414.0 2011-05-09 13:49:00
           116217  Bahrain    19.8  414.0 2011-05-09 13:49:00
           116218  Bahrain    17.7  414.0 2011-05-09 13:49:00
           116219  Bahrain    17.7  414.0 2011-05-09 13:49:00
           116220  Bahrain    17.7  414.0 2011-05-09 13:49:00
           116221  Bahrain    25.5  414.0 2011-05-09 13:49:00
           116222  Bahrain    25.5  414.0 2011-05-09 13:49:00
           116223  Bahrain    25.5  414.0 2011-05-09 13:49:00

                  first_purchase_date  num_purchases  monetary  cust_total  \
CustomerID
12355.0    116213 2011-05-09 13:49:00              1    4554.0        30.0
           116214 2011-05-09 13:49:00              1    4554.0       120.0
           116215 2011-05-09 13:49:00              1    4554.0        75.0
           116216 2011-05-09 13:49:00              1    4554.0        39.6
           116217 2011-05-09 13:49:00              1    4554.0        19.8
           116218 2011-05-09 13:49:00              1    4554.0        17.7
           116219 2011-05-09 13:49:00              1    4554.0        17.7
           116220 2011-05-09 13:49:00              1    4554.0        17.7
           116221 2011-05-09 13:49:00              1    4554.0        25.5
           116222 2011-05-09 13:49:00              1    4554.0        25.5
           116223 2011-05-09 13:49:00              1    4554.0        25.5

                     ttl
CustomerID
12355.0    116213  414.0
           116214  414.0
           116215  414.0
           116216  414.0
           116217  414.0
           116218  414.0
           116219  414.0
           116220  414.0
           116221  414.0
           116222  414.0
           116223  414.0

In [33]:
NEW_DATA.drop('monetary',axis=1,inplace=True)

In [34]:
NEW_DATA.rename({'ttl':'monetary'},axis=1)

                   InvoiceNo StockCode                          Description  \
CustomerID
12346.0    34769      541431     23166       MEDIUM CERAMIC TOP STORAGE JAR
12347.0    9890       537626     85116      BLACK CANDELABRA T-LIGHT HOLDER
           9891       537626     22375    AIRLINE BAG VINTAGE JET SET BROWN
           9892       537626     71477    COLOUR GLASS. STAR T-LIGHT HOLDER
           9893       537626     22492              MINI PAINT SET VINTAGE
...                      ...       ...                                  ...
18287.0    267342     570715     22419                     LIPSTICK PEN RED
           267343     570715     22866        HAND WARMER SCOTTY DOG DESIGN
           291570     573167     23264   SET OF 3 WOODEN SLEIGH DECORATIONS
           291571     573167     21824  PAINTED METAL STAR WITH HOLLY BELLS
           291572     573167     21014        SWISS CHALET TREE DECORATION

                   Quantity         InvoiceDate  UnitPrice  CustomerID  \
CustomerID
12346.0    34769      74215 2011-01-18 10:01:00       1.04     12346.0
12347.0    9890          12 2010-12-07 14:57:00       2.10     12347.0
           9891           4 2010-12-07 14:57:00       4.25     12347.0
           9892          12 2010-12-07 14:57:00       3.25     12347.0
           9893          36 2010-12-07 14:57:00       0.65     12347.0
...                     ...                 ...        ...         ...
18287.0    267342        12 2011-10-12 10:23:00       0.42     18287.0
           267343        12 2011-10-12 10:23:00       2.10     18287.0
           291570        36 2011-10-28 09:29:00       1.25     18287.0
           291571        48 2011-10-28 09:29:00       0.39     18287.0
           291572        24 2011-10-28 09:29:00       0.29     18287.0

                          Country    Amount     Total  last_purchase_date  \
CustomerID
12346.0    34769   United Kingdom  77183.60  77183.60 2011-01-18 10:01:00
12347.0    9890           Iceland     25.20    711.79 2011-12-07 15:52:00
           9891           Iceland     17.00    711.79 2011-12-07 15:52:00
           9892           Iceland     39.00    711.79 2011-12-07 15:52:00
           9893           Iceland     23.40    711.79 2011-12-07 15:52:00
...                           ...       ...       ...                 ...
18287.0    267342  United Kingdom      5.04   1001.32 2011-10-28 09:29:00
           267343  United Kingdom     25.20   1001.32 2011-10-28 09:29:00
           291570  United Kingdom     45.00     70.68 2011-10-28 09:29:00
           291571  United Kingdom     18.72     70.68 2011-10-28 09:29:00
           291572  United Kingdom      6.96     70.68 2011-10-28 09:29:00

                  first_purchase_date  num_purchases  cust_total  monetary
CustomerID
12346.0    34769  2011-01-18 10:01:00              1    77183.60  77183.60
12347.0    9890   2010-12-07 14:57:00              7       25.20   4078.95
           9891   2010-12-07 14:57:00              7       17.00   4078.95
           9892   2010-12-07 14:57:00              7       39.00   4078.95
           9893   2010-12-07 14:57:00              7       23.40   4078.95
...                               ...            ...         ...       ...
18287.0    267342 2011-05-22 10:39:00              3        5.04   1803.28
           267343 2011-05-22 10:39:00              3       25.20   1803.28
           291570 2011-05-22 10:39:00              3       45.00   1803.28
           291571 2011-05-22 10:39:00              3       18.72   1803.28
           291572 2011-05-22 10:39:00              3        6.96   1803.28

[375187 rows x 15 columns]

In [35]:
NEW_DATA.reset_index(drop=True,inplace=True)

In [36]:
NEW_DATA

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,ttl
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18 10:01:00,2011-01-18 10:01:00,1,77183.60,77183.60
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,25.20,4078.95
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,17.00,4078.95
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,39.00,4078.95
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07 15:52:00,2010-12-07 14:57:00,7,23.40,4078.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28 09:29:00,2011-05-22 10:39:00,3,5.04,1803.28
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28 09:29:00,2011-05-22 10:39:00,3,25.20,1803.28
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28 09:29:00,2011-05-22 10:39:00,3,45.00,1803.28
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28 09:29:00,2011-05-22 10:39:00,3,18.72,1803.28
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28 09:29:00,2011-05-22 10:39:00,3,6.96,1803.28

In [37]:
NEW_DATA['last_purchase_date']=NEW_DATA['last_purchase_date'].dt.date
NEW_DATA['first_purchase_date']=NEW_DATA['first_purchase_date'].dt.date
NEW_DATA

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,ttl
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28

In [38]:
NEW_DATA['last_purchase_date']=pd.to_datetime(NEW_DATA['last_purchase_date'])
NEW_DATA['first_purchase_date']=pd.to_datetime(NEW_DATA['first_purchase_date'])

In [39]:
NEW_DATA

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,ttl
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28

In [40]:
NEW_DATA['last_purchase_date'].dtype

dtype('<M8[ns]')

In [41]:
NEW_DATA['months_cust']=(NEW_DATA['last_purchase_date']-NEW_DATA['first_purchase_date']).dt.days

In [42]:
NEW_DATA['months_cust'] = NEW_DATA['months_cust'].astype('int')/30

In [43]:
NEW_DATA['months_cust']=NEW_DATA['months_cust']+1

In [44]:
NEW_DATA['months_cust'].str.split(' ')

AttributeError: Can only use .str accessor with string values!

In [45]:
NEW_DATA['months_cust']=NEW_DATA['months_cust'].astype(str)

In [46]:
NEW_DATA['months_cust1']=NEW_DATA['months_cust'].str.split(' ')

In [47]:
NEW_DATA['months_cust1']=NEW_DATA['months_cust1'].str[0]

In [48]:
NEW_DATA['months_cust1']

0                        1.0
1         13.166666666666666
2         13.166666666666666
3         13.166666666666666
4         13.166666666666666
                 ...
375182                   6.3
375183                   6.3
375184                   6.3
375185                   6.3
375186                   6.3
Name: months_cust1, Length: 375187, dtype: object

In [49]:
NEW_DATA['months_cust2']=NEW_DATA['months_cust1'].str.split(':')

In [50]:
NEW_DATA['months_cust2']

0                        [1.0]
1         [13.166666666666666]
2         [13.166666666666666]
3         [13.166666666666666]
4         [13.166666666666666]
                  ...
375182                   [6.3]
375183                   [6.3]
375184                   [6.3]
375185                   [6.3]
375186                   [6.3]
Name: months_cust2, Length: 375187, dtype: object

In [51]:
NEW_DATA

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,ttl,months_cust,months_cust1,months_cust2
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60,1.0,1.0,[1.0]
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95,13.166666666666666,13.166666666666666,[13.166666666666666]
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95,13.166666666666666,13.166666666666666,[13.166666666666666]
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95,13.166666666666666,13.166666666666666,[13.166666666666666]
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95,13.166666666666666,13.166666666666666,[13.166666666666666]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28,6.3,6.3,[6.3]
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28,6.3,6.3,[6.3]
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28,6.3,6.3,[6.3]
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28,6.3,6.3,[6.3]
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28,6.3,6.3,[6.3]

In [52]:
DF=NEW_DATA.copy()

In [53]:
DF.drop(['months_cust1','months_cust2'],axis =1,inplace=True)

In [54]:
DF.rename({'ttl':'monetary'},axis=1,inplace=True)

In [55]:
DF

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,monetary,months_cust
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60,1.0
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95,13.166666666666666
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95,13.166666666666666
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95,13.166666666666666
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95,13.166666666666666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28,6.3
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28,6.3
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28,6.3
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28,6.3
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28,6.3

In [56]:
DF['max_date']=DF['last_purchase_date'].dt.date.max()

In [57]:
DF

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,monetary,months_cust,max_date
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60,1.0,2011-12-09
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95,13.166666666666666,2011-12-09
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95,13.166666666666666,2011-12-09
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95,13.166666666666666,2011-12-09
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95,13.166666666666666,2011-12-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28,6.3,2011-12-09
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28,6.3,2011-12-09
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28,6.3,2011-12-09
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28,6.3,2011-12-09
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28,6.3,2011-12-09

In [58]:
DF['max_date']=pd.to_datetime(DF['max_date'])

In [59]:
DF['last_purchase_date'].dtype

dtype('<M8[ns]')

In [60]:
DF['months_cust'].dtype

dtype('O')

In [63]:
DF['months_cust']=DF['months_cust'].astype(float)

In [64]:
DF['recency']=(DF['max_date']-DF['last_purchase_date']).dt.days+1
DF['frequency']=DF['num_purchases']/DF['months_cust']
DF

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,monetary,months_cust,max_date,recency,frequency
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60,1.000000,2011-12-09,326,1.000000
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95,13.166667,2011-12-09,3,0.531646
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95,13.166667,2011-12-09,3,0.531646
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95,13.166667,2011-12-09,3,0.531646
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95,13.166667,2011-12-09,3,0.531646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28,6.300000,2011-12-09,43,0.476190
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28,6.300000,2011-12-09,43,0.476190
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28,6.300000,2011-12-09,43,0.476190
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28,6.300000,2011-12-09,43,0.476190
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28,6.300000,2011-12-09,43,0.476190

In [65]:
DF[DF['CustomerID']==12356]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,monetary,months_cust,max_date,recency,frequency
415,541430,22138,BAKING SET 9 PIECE RETROSPOT,24,2011-01-18 09:50:00,4.25,12356.0,Portugal,102.00,1524.74,2011-04-08,2011-01-18,2,102.00,1911.4,3.666667,2011-12-09,246,0.545455
416,541430,21198,WHITE HEART CONFETTI IN TUBE,48,2011-01-18 09:50:00,0.42,12356.0,Portugal,20.16,1524.74,2011-04-08,2011-01-18,2,20.16,1911.4,3.666667,2011-12-09,246,0.545455
417,541430,21114,LAVENDER SCENTED FABRIC HEART,40,2011-01-18 09:50:00,1.25,12356.0,Portugal,50.00,1524.74,2011-04-08,2011-01-18,2,50.00,1911.4,3.666667,2011-12-09,246,0.545455
418,541430,21199,PINK HEART CONFETTI IN TUBE,48,2011-01-18 09:50:00,0.42,12356.0,Portugal,20.16,1524.74,2011-04-08,2011-01-18,2,20.16,1911.4,3.666667,2011-12-09,246,0.545455
419,541430,21231,SWEETHEART CERAMIC TRINKET BOX,72,2011-01-18 09:50:00,1.06,12356.0,Portugal,76.32,1524.74,2011-04-08,2011-01-18,2,76.32,1911.4,3.666667,2011-12-09,246,0.545455
420,541430,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,24,2011-01-18 09:50:00,2.95,12356.0,Portugal,70.80,1524.74,2011-04-08,2011-01-18,2,70.80,1911.4,3.666667,2011-12-09,246,0.545455
421,541430,22066,LOVE HEART TRINKET POT,24,2011-01-18 09:50:00,1.45,12356.0,Portugal,34.80,1524.74,2011-04-08,2011-01-18,2,34.80,1911.4,3.666667,2011-12-09,246,0.545455
422,541430,22132,RED LOVE HEART SHAPE CUP,48,2011-01-18 09:50:00,0.85,12356.0,Portugal,40.80,1524.74,2011-04-08,2011-01-18,2,40.80,1911.4,3.666667,2011-12-09,246,0.545455
423,541430,22131,FOOD CONTAINER SET 3 LOVE HEART,24,2011-01-18 09:50:00,1.95,12356.0,Portugal,46.80,1524.74,2011-04-08,2011-01-18,2,46.80,1911.4,3.666667,2011-12-09,246,0.545455
424,541430,22195,LARGE HEART MEASURING SPOONS,12,2011-01-18 09:50:00,1.65,12356.0,Portugal,19.80,1524.74,2011-04-08,2011-01-18,2,19.80,1911.4,3.666667,2011-12-09,246,0.545455
425,541430,22435,SET OF 9 HEART SHAPED BALLOONS,60,2011-01-18 09:50:00,1.25,12356.0,Portugal,75.00,1524.74,2011-04-08,2011-01-18,2,75.00,1911.4,3.666667,2011-12-09,246,0.545455
426,541430,22937,BAKING MOULD CHOCOLATE CUPCAKES,24,2011-01-18 09:50:00,2.55,12356.0,Portugal,61.20,1524.74,2011-04-08,2011-01-18,2,61.20,1911.4,3.666667,2011-12-09,246,0.545455
427,541430,84378,SET OF 3 HEART COOKIE CUTTERS,48,2011-01-18 09:50:00,1.25,12356.0,Portugal,60.00,1524.74,2011-04-08,2011-01-18,2,60.00,1911.4,3.666667,2011-12-09,246,0.545455
428,541430,84569D,PACK 6 HEART/ICE-CREAM PATCHES,24,2011-01-18 09:50:00,1.25,12356.0,Portugal,30.00,1524.74,2011-04-08,2011-01-18,2,30.00,1911.4,3.666667,2011-12-09,246,0.545455
429,541430,84992,72 SWEETHEART FAIRY CAKE CASES,120,2011-01-18 09:50:00,0.42,12356.0,Portugal,50.40,1524.74,2011-04-08,2011-01-18,2,50.40,1911.4,3.666667,2011-12-09,246,0.545455
430,541430,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,24,2011-01-18 09:50:00,1.25,12356.0,Portugal,30.00,1524.74,2011-04-08,2011-01-18,2,30.00,1911.4,3.666667,2011-12-09,246,0.545455
431,541430,22055,MINI CAKE STAND HANGING STRAWBERY,32,2011-01-18 09:50:00,1.45,12356.0,Portugal,46.40,1524.74,2011-04-08,2011-01-18,2,46.40,1911.4,3.666667,2011-12-09,246,0.545455
432,541430,22059,CERAMIC STRAWBERRY DESIGN MUG,48,2011-01-18 09:50:00,1.25,12356.0,Portugal,60.00,1524.74,2011-04-08,2011-01-18,2,60.00,1911.4,3.666667,2011-12-09,246,0.545455
433,541430,22649,STRAWBERRY FAIRY CAKE TEAPOT,24,2011-01-18 09:50:00,4.25,12356.0,Portugal,102.00,1524.74,2011-04-08,2011-01-18,2,102.00,1911.4,3.666667,2011-12-09,246,0.545455
434,541430,22646,CERAMIC STRAWBERRY CAKE MONEY BANK,12,2011-01-18 09:50:00,1.45,12356.0,Portugal,17.40,1524.74,2011-04-08,2011-01-18,2,17.40,1911.4,3.666667,2011-12-09,246,0.545455
435,541430,37448,CERAMIC CAKE DESIGN SPOTTED MUG,48,2011-01-18 09:50:00,1.25,12356.0,Portugal,60.00,1524.74,2011-04-08,2011-01-18,2,60.00,1911.4,3.666667,2011-12-09,246,0.545455
436,541430,37450,CERAMIC CAKE BOWL + HANGING CAKES,18,2011-01-18 09:50:00,2.55,12356.0,Portugal,45.90,1524.74,2011-04-08,2011-01-18,2,45.90,1911.4,3.666667,2011-12-09,246,0.545455
437,541430,37501,TEA TIME TEA SET IN GIFT BOX,12,2011-01-18 09:50:00,6.95,12356.0,Portugal,83.40,1524.74,2011-04-08,2011-01-18,2,83.40,1911.4,3.666667,2011-12-09,246,0.545455
438,541430,84991,60 TEATIME FAIRY CAKE CASES,120,2011-01-18 09:50:00,0.42,12356.0,Portugal,50.40,1524.74,2011-04-08,2011-01-18,2,50.40,1911.4,3.666667,2011-12-09,246,0.545455
439,541430,84987,SET OF 36 TEATIME PAPER DOILIES,24,2011-01-18 09:50:00,1.45,12356.0,Portugal,34.80,1524.74,2011-04-08,2011-01-18,2,34.80,1911.4,3.666667,2011-12-09,246,0.545455
440,541430,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,32,2011-01-18 09:50:00,0.65,12356.0,Portugal,20.80,1524.74,2011-04-08,2011-01-18,2,20.80,1911.4,3.666667,2011-12-09,246,0.545455
441,541430,84375,SET OF 20 KIDS COOKIE CUTTERS,36,2011-01-18 09:50:00,2.10,12356.0,Portugal,75.60,1524.74,2011-04-08,2011-01-18,2,75.60,1911.4,3.666667,2011-12-09,246,0.545455
442,541430,84380,SET OF 3 BUTTERFLY COOKIE CUTTERS,24,2011-01-18 09:50:00,1.25,12356.0,Portugal,30.00,1524.74,2011-04-08,2011-01-18,2,30.00,1911.4,3.666667,2011-12-09,246,0.545455
443,541430,22951,60 CAKE CASES DOLLY GIRL DESIGN,24,2011-01-18 09:50:00,0.55,12356.0,Portugal,13.20,1524.74,2011-04-08,2011-01-18,2,13.20,1911.4,3.666667,2011-12-09,246,0.545455
444,541430,21213,PACK OF 72 SKULL CAKE CASES,24,2011-01-18 09:50:00,0.55,12356.0,Portugal,13.20,1524.74,2011-04-08,2011-01-18,2,13.20,1911.4,3.666667,2011-12-09,246,0.545455
445,541430,21527,RED RETROSPOT TRADITIONAL TEAPOT,12,2011-01-18 09:50:00,6.95,12356.0,Portugal,83.40,1524.74,2011-04-08,2011-01-18,2,83.40,1911.4,3.666667,2011-12-09,246,0.545455
446,549435,84991,60 TEATIME FAIRY CAKE CASES,48,2011-04-08 12:33:00,0.55,12356.0,Portugal,26.40,386.66,2011-04-08,2011-01-18,2,26.40,1911.4,3.666667,2011-12-09,246,0.545455
447,549435,21212,PACK OF 72 RETROSPOT CAKE CASES,24,2011-04-08 12:33:00,0.55,12356.0,Portugal,13.20,386.66,2011-04-08,2011-01-18,2,13.20,1911.4,3.666667,2011-12-09,246,0.545455
448,549435,22938,CUPCAKE LACE PAPER SET 6,12,2011-04-08 12:33:00,1.95,12356.0,Portugal,23.40,386.66,2011-04-08,2011-01-18,2,23.40,1911.4,3.666667,2011-12-09,246,0.545455
449,549435,21124,SET/10 BLUE POLKADOT PARTY CANDLES,24,2011-04-08 12:33:00,1.25,12356.0,Portugal,30.00,386.66,2011-04-08,2011-01-18,2,30.00,1911.4,3.666667,2011-12-09,246,0.545455
450,549435,84457,SET/3 RABBITS FLOWER SKIPPPING ROPE,20,2011-04-08 12:33:00,0.85,12356.0,Portugal,17.00,386.66,2011-04-08,2011-01-18,2,17.00,1911.4,3.666667,2011-12-09,246,0.545455
451,549435,22857,ASSORTED EASTER GIFT TAGS,72,2011-04-08 12:33:00,0.85,12356.0,Portugal,61.20,386.66,2011-04-08,2011-01-18,2,61.20,1911.4,3.666667,2011-12-09,246,0.545455
452,549435,21122,SET/10 PINK POLKADOT PARTY CANDLES,24,2011-04-08 12:33:00,1.25,12356.0,Portugal,30.00,386.66,2011-04-08,2011-01-18,2,30.00,1911.4,3.666667,2011-12-09,246,0.545455
453,549435,21125,SET 6 FOOTBALL CELEBRATION CANDLES,12,2011-04-08 12:33:00,1.25,12356.0,Portugal,15.00,386.66,2011-04-08,2011-01-18,2,15.00,1911.4,3.666667,2011-12-09,246,0.545455
454,549435,22967,SET 3 SONG BIRD PAPER EGGS ASSORTED,12,2011-04-08 12:33:00,2.95,12356.0,Portugal,35.40,386.66,2011-04-08,2011-01-18,2,35.40,1911.4,3.666667,2011-12-09,246,0.545455
455,549435,22957,SET 3 PAPER VINTAGE CHICK PAPER EGG,12,2011-04-08 12:33:00,2.95,12356.0,Portugal,35.40,386.66,2011-04-08,2011-01-18,2,35.40,1911.4,3.666667,2011-12-09,246,0.545455
456,549435,21086,SET/6 RED SPOTTY PAPER CUPS,6,2011-04-08 12:33:00,0.65,12356.0,Portugal,3.90,386.66,2011-04-08,2011-01-18,2,3.90,1911.4,3.666667,2011-12-09,246,0.545455
457,549435,21080,SET/20 RED RETROSPOT PAPER NAPKINS,15,2011-04-08 12:33:00,0.85,12356.0,Portugal,12.75,386.66,2011-04-08,2011-01-18,2,12.75,1911.4,3.666667,2011-12-09,246,0.545455
458,549435,20971,PINK BLUE FELT CRAFT TRINKET BOX,8,2011-04-08 12:33:00,1.25,12356.0,Portugal,10.00,386.66,2011-04-08,2011-01-18,2,10.00,1911.4,3.666667,2011-12-09,246,0.545455
459,549435,84378,SET OF 3 HEART COOKIE CUTTERS,3,2011-04-08 12:33:00,1.25,12356.0,Portugal,3.75,386.66,2011-04-08,2011-01-18,2,3.75,1911.4,3.666667,2011-12-09,246,0.545455
460,549435,21094,SET/6 RED SPOTTY PAPER PLATES,10,2011-04-08 12:33:00,0.85,12356.0,Portugal,8.50,386.66,2011-04-08,2011-01-18,2,8.50,1911.4,3.666667,2011-12-09,246,0.545455
461,549435,37447,CERAMIC CAKE DESIGN SPOTTED PLATE,4,2011-04-08 12:33:00,1.49,12356.0,Portugal,5.96,386.66,2011-04-08,2011-01-18,2,5.96,1911.4,3.666667,2011-12-09,246,0.545455
462,549435,21383,PACK OF 12 STICKY BUNNIES,48,2011-04-08 12:33:00,0.65,12356.0,Portugal,31.20,386.66,2011-04-08,2011-01-18,2,31.20,1911.4,3.666667,2011-12-09,246,0.545455
463,549435,22698,PINK REGENCY TEACUP AND SAUCER,4,2011-04-08 12:33:00,2.95,12356.0,Portugal,11.80,386.66,2011-04-08,2011-01-18,2,11.80,1911.4,3.666667,2011-12-09,246,0.545455
464,549435,22699,ROSES REGENCY TEACUP AND SAUCER,4,2011-04-08 12:33:00,2.95,12356.0,Portugal,11.80,386.66,2011-04-08,2011-01-18,2,11.80,1911.4,3.666667,2011-12-09,246,0.545455

In [70]:
DF['m20']=DF['monetary'].quantile(0.2)

In [71]:
DF

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,monetary,months_cust,max_date,recency,frequency,m20
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,77183.60,2011-01-18,2011-01-18,1,77183.60,77183.60,1.000000,2011-12-09,326,1.000000,784.58
1,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20,711.79,2011-12-07,2010-12-07,7,25.20,4078.95,13.166667,2011-12-09,3,0.531646,784.58
2,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00,711.79,2011-12-07,2010-12-07,7,17.00,4078.95,13.166667,2011-12-09,3,0.531646,784.58
3,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00,711.79,2011-12-07,2010-12-07,7,39.00,4078.95,13.166667,2011-12-09,3,0.531646,784.58
4,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40,711.79,2011-12-07,2010-12-07,7,23.40,4078.95,13.166667,2011-12-09,3,0.531646,784.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375182,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287.0,United Kingdom,5.04,1001.32,2011-10-28,2011-05-22,3,5.04,1803.28,6.300000,2011-12-09,43,0.476190,784.58
375183,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287.0,United Kingdom,25.20,1001.32,2011-10-28,2011-05-22,3,25.20,1803.28,6.300000,2011-12-09,43,0.476190,784.58
375184,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287.0,United Kingdom,45.00,70.68,2011-10-28,2011-05-22,3,45.00,1803.28,6.300000,2011-12-09,43,0.476190,784.58
375185,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287.0,United Kingdom,18.72,70.68,2011-10-28,2011-05-22,3,18.72,1803.28,6.300000,2011-12-09,43,0.476190,784.58
375186,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287.0,United Kingdom,6.96,70.68,2011-10-28,2011-05-22,3,6.96,1803.28,6.300000,2011-12-09,43,0.476190,784.58

In [72]:
DF[DF['CustomerID']==12346]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Total,last_purchase_date,first_purchase_date,num_purchases,cust_total,monetary,months_cust,max_date,recency,frequency,m20
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.6,77183.6,2011-01-18,2011-01-18,1,77183.6,77183.6,1.0,2011-12-09,326,1.0,784.58

In [79]:
DF['monetary'].max()

266194.22000000003

In [80]:
cust_seg=DF[['CustomerID','Country','monetary','recency','frequency']]

In [81]:
cust_seg

        CustomerID         Country  monetary  recency  frequency
0          12346.0  United Kingdom  77183.60      326   1.000000
1          12347.0         Iceland   4078.95        3   0.531646
2          12347.0         Iceland   4078.95        3   0.531646
3          12347.0         Iceland   4078.95        3   0.531646
4          12347.0         Iceland   4078.95        3   0.531646
...            ...             ...       ...      ...        ...
375182     18287.0  United Kingdom   1803.28       43   0.476190
375183     18287.0  United Kingdom   1803.28       43   0.476190
375184     18287.0  United Kingdom   1803.28       43   0.476190
375185     18287.0  United Kingdom   1803.28       43   0.476190
375186     18287.0  United Kingdom   1803.28       43   0.476190

[375187 rows x 5 columns]

In [86]:
cust_seg.drop_duplicates(inplace=True)

<ipython-input-86-24af39624cf9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg.drop_duplicates(inplace=True)

In [93]:
cust_seg.reset_index(drop=True,inplace=True)

In [94]:
cust_seg['monetary'].quantile(0.2)

218.34400000000005

In [97]:
cust_seg.drop('index',axis=1,inplace=True)

<ipython-input-97-e12e0416e4cb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg.drop('index',axis=1,inplace=True)

In [98]:
cust_seg

      CustomerID         Country  monetary  recency  frequency
0        12346.0  United Kingdom  77183.60      326   1.000000
1        12347.0         Iceland   4078.95        3   0.531646
2        12348.0         Finland   1437.24       76   0.383387
3        12349.0           Italy   1287.15       19   1.000000
4        12350.0          Norway    294.40      311   1.000000
...          ...             ...       ...      ...        ...
4314     18280.0  United Kingdom    160.70      278   1.000000
4315     18281.0  United Kingdom     46.92      181   1.000000
4316     18282.0  United Kingdom    127.05        8   0.402685
4317     18283.0  United Kingdom   2051.98        4   1.318681
4318     18287.0  United Kingdom   1803.28       43   0.476190

[4319 rows x 5 columns]

In [99]:
cust_seg['m20']=cust_seg['monetary'].quantile(0.2)
cust_seg['m40']=cust_seg['monetary'].quantile(0.4)
cust_seg['m60']=cust_seg['monetary'].quantile(0.6)
cust_seg['m80']=cust_seg['monetary'].quantile(0.8)
cust_seg['m100']=cust_seg['monetary'].quantile(1)

<ipython-input-99-592741f3ee37>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['m20']=cust_seg['monetary'].quantile(0.2)
<ipython-input-99-592741f3ee37>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['m40']=cust_seg['monetary'].quantile(0.4)
<ipython-input-99-592741f3ee37>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['m60']=cust_seg['monetary'].quantile(0.6)
<ipython-input-99-592741f3ee37>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['m80']=cust_seg['monetary'].quantile(0.8)
<ipython-input-99-592741f3ee37>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['m100']=cust_seg['monetary'].quantile(1)

In [100]:
cust_seg

,CustomerID,Country,monetary,recency,frequency,m20,m40,m60,m80,m100
0,12346.0,United Kingdom,77183.60,326,1.000000,218.344,428.914,845.726,1864.592,266194.22
1,12347.0,Iceland,4078.95,3,0.531646,218.344,428.914,845.726,1864.592,266194.22
2,12348.0,Finland,1437.24,76,0.383387,218.344,428.914,845.726,1864.592,266194.22
3,12349.0,Italy,1287.15,19,1.000000,218.344,428.914,845.726,1864.592,266194.22
4,12350.0,Norway,294.40,311,1.000000,218.344,428.914,845.726,1864.592,266194.22
...,...,...,...,...,...,...,...,...,...,...
4314,18280.0,United Kingdom,160.70,278,1.000000,218.344,428.914,845.726,1864.592,266194.22
4315,18281.0,United Kingdom,46.92,181,1.000000,218.344,428.914,845.726,1864.592,266194.22
4316,18282.0,United Kingdom,127.05,8,0.402685,218.344,428.914,845.726,1864.592,266194.22
4317,18283.0,United Kingdom,2051.98,4,1.318681,218.344,428.914,845.726,1864.592,266194.22
4318,18287.0,United Kingdom,1803.28,43,0.476190,218.344,428.914,845.726,1864.592,266194.22

In [101]:
cust_seg['r20']=cust_seg['recency'].quantile(0.2)
cust_seg['r40']=cust_seg['recency'].quantile(0.4)
cust_seg['r60']=cust_seg['recency'].quantile(0.6)
cust_seg['r80']=cust_seg['recency'].quantile(0.8)
cust_seg['r100']=cust_seg['recency'].quantile(1)
cust_seg['f20']=cust_seg['frequency'].quantile(0.2)
cust_seg['f40']=cust_seg['frequency'].quantile(0.4)
cust_seg['f60']=cust_seg['frequency'].quantile(0.6)
cust_seg['f80']=cust_seg['frequency'].quantile(0.8)
cust_seg['f100']=cust_seg['frequency'].quantile(1)

<ipython-input-101-46088430efea>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['r20']=cust_seg['recency'].quantile(0.2)
<ipython-input-101-46088430efea>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['r40']=cust_seg['recency'].quantile(0.4)
<ipython-input-101-46088430efea>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['r60']=cust_seg['recency'].quantile(0.6)
<ipython-input-101-46088430efea>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['r80']=cust_seg['recency'].quantile(0.8)
<ipython-input-101-46088430efea>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['r100']=cust_seg['recency'].quantile(1)
<ipython-input-101-46088430efea>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['f20']=cust_seg['frequency'].quantile(0.2)
<ipython-input-101-46088430efea>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['f40']=cust_seg['frequency'].quantile(0.4)
<ipython-input-101-46088430efea>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['f60']=cust_seg['frequency'].quantile(0.6)
<ipython-input-101-46088430efea>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['f80']=cust_seg['frequency'].quantile(0.8)
<ipython-input-101-46088430efea>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_seg['f100']=cust_seg['frequency'].quantile(1)

In [102]:
cust_seg

,CustomerID,Country,monetary,recency,frequency,m20,m40,m60,m80,m100,r20,r40,r60,r80,r100,f20,f40,f60,f80,f100
0,12346.0,United Kingdom,77183.60,326,1.000000,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
1,12347.0,Iceland,4078.95,3,0.531646,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
2,12348.0,Finland,1437.24,76,0.383387,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
3,12349.0,Italy,1287.15,19,1.000000,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
4,12350.0,Norway,294.40,311,1.000000,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,18280.0,United Kingdom,160.70,278,1.000000,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
4315,18281.0,United Kingdom,46.92,181,1.000000,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
4316,18282.0,United Kingdom,127.05,8,0.402685,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
4317,18283.0,United Kingdom,2051.98,4,1.318681,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226
4318,18287.0,United Kingdom,1803.28,43,0.476190,218.344,428.914,845.726,1864.592,266194.22,14.2,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226

In [117]:
def func1(x):
  if x['monetary']<=x['m20']:
    x['m_score']=1
  elif x['monetary']<=x['m40'] and x['monetary']>x['m20']:
    x['m_score']=2
  elif x['monetary']<=x['m60'] and x['monetary']>x['m40']:
    x['m_score']=3
  elif x['monetary']<=x['m80'] and x['monetary']>x['m60']:
    x['m_score']=4
  else:
    x['m_score']=5
  return x

In [138]:
def func2(x):
  if x['recency']<=x['r20']:
    x['r_score']=5
  elif x['recency']<=x['r40'] and x['recency']>x['r20']:
    x['r_score']=4
  elif x['recency']<=x['r60'] and x['recency']>x['r40']:
    x['r_score']=3
  elif x['recency']<=x['r80'] and x['recency']>x['r60']:
    x['r_score']=2
  else:
    x['r_score']=1
  return x

In [119]:
def func3(x):
  if x['frequency']<=x['f20']:
    x['f_score']=1
  elif x['frequency']<=x['f40'] and x['frequency']>x['f20']:
    x['f_score']=2
  elif x['frequency']<=x['f60'] and x['frequency']>x['f40']:
    x['f_score']=3
  elif x['frequency']<=x['f80'] and x['frequency']>x['f60']:
    x['f_score']=4
  else:
    x['f_score']=5
  return x

In [139]:
cust_seg1=cust_seg.apply(func2,axis=1)

In [140]:
cust_seg1

,CustomerID,Country,monetary,recency,frequency,m20,m40,m60,m80,m100,...,r40,r60,r80,r100,f20,f40,f60,f80,f100,r_score
0,12346.0,United Kingdom,77183.60,326,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1
1,12347.0,Iceland,4078.95,3,0.531646,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,5
2,12348.0,Finland,1437.24,76,0.383387,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,2
3,12349.0,Italy,1287.15,19,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,4
4,12350.0,Norway,294.40,311,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,18280.0,United Kingdom,160.70,278,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1
4315,18281.0,United Kingdom,46.92,181,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1
4316,18282.0,United Kingdom,127.05,8,0.402685,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,5
4317,18283.0,United Kingdom,2051.98,4,1.318681,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,5
4318,18287.0,United Kingdom,1803.28,43,0.476190,218.344,428.914,845.726,1864.592,266194.22,...,33.0,72.0,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,3

In [141]:
cust_seg2=cust_seg1.apply(func1,axis=1)

In [142]:
cust_seg3=cust_seg2.apply(func3,axis=1)

In [143]:
cust_seg3

,CustomerID,Country,monetary,recency,frequency,m20,m40,m60,m80,m100,...,r80,r100,f20,f40,f60,f80,f100,r_score,m_score,f_score
0,12346.0,United Kingdom,77183.60,326,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,5,3
1,12347.0,Iceland,4078.95,3,0.531646,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,5,5,2
2,12348.0,Finland,1437.24,76,0.383387,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,2,4,1
3,12349.0,Italy,1287.15,19,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,4,4,3
4,12350.0,Norway,294.40,311,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,18280.0,United Kingdom,160.70,278,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,1,3
4315,18281.0,United Kingdom,46.92,181,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,1,3
4316,18282.0,United Kingdom,127.05,8,0.402685,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,5,1,1
4317,18283.0,United Kingdom,2051.98,4,1.318681,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,5,5,5
4318,18287.0,United Kingdom,1803.28,43,0.476190,218.344,428.914,845.726,1864.592,266194.22,...,178.4,374.0,0.461538,0.763775,1.0,1.0,32.903226,3,4,2

In [144]:
cust_seg3['fm_score']=round((cust_seg3['f_score']+cust_seg3['m_score'])/2,0)

In [146]:
cust_seg3

,CustomerID,Country,monetary,recency,frequency,m20,m40,m60,m80,m100,...,r100,f20,f40,f60,f80,f100,r_score,m_score,f_score,fm_score
0,12346.0,United Kingdom,77183.60,326,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,5,3,4.0
1,12347.0,Iceland,4078.95,3,0.531646,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,5,5,2,4.0
2,12348.0,Finland,1437.24,76,0.383387,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,2,4,1,2.0
3,12349.0,Italy,1287.15,19,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,4,4,3,4.0
4,12350.0,Norway,294.40,311,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,2,3,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,18280.0,United Kingdom,160.70,278,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,1,3,2.0
4315,18281.0,United Kingdom,46.92,181,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,1,1,3,2.0
4316,18282.0,United Kingdom,127.05,8,0.402685,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,5,1,1,1.0
4317,18283.0,United Kingdom,2051.98,4,1.318681,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,5,5,5,5.0
4318,18287.0,United Kingdom,1803.28,43,0.476190,218.344,428.914,845.726,1864.592,266194.22,...,374.0,0.461538,0.763775,1.0,1.0,32.903226,3,4,2,3.0

In [147]:
def func4(x):
  if (x['r_score']==5 and x['fm_score']==5) or (x['r_score']==5 and x['fm_score']==4) or (x['r_score']==4 and x['fm_score']==5):
    x['rfm_segment']='Champions'
  elif (x['r_score']==5 and x['fm_score']==3) or (x['r_score']==4 and x['fm_score']==4) or (x['r_score']==3 and x['fm_score']==5) or (x['r_score']==3 and x['fm_score']==4):
    x['rfm_segment']='Loyal Customers'
  elif (x['r_score']==5 and x['fm_score']==2) or (x['r_score']==4 and x['fm_score']==2) or (x['r_score']==3 and x['fm_score']==3) or (x['r_score']==4 and x['fm_score']==3):
    x['rfm_segment']='Potential Loyalists'
  elif x['r_score']==5 and x['fm_score']==1:
    x['rfm_segment']='Recent Customers'
  elif (x['r_score']==4 and x['fm_score']==1) or (x['r_score']==3 and x['fm_score']==1):
    x['rfm_segment']='Promising'
  elif (x['r_score']==3 and x['fm_score']==2) or (x['r_score']==2 and x['fm_score']==3) or (x['r_score']==2 and x['fm_score']==2):
    x['rfm_segment']='Customer Needing Attention'
  elif (x['r_score']==2 and x['fm_score']==1):
    x['rfm_segment']='About to Sleep'
  elif (x['r_score']==2 and x['fm_score']==5) or (x['r_score']==2 and x['fm_score']==4) or (x['r_score']==1 and x['fm_score']==3):
    x['rfm_segment']='At Risk'
  elif (x['r_score']==1 and x['fm_score']==5) or (x['r_score']==1 and x['fm_score']==4):
    x['rfm_segment']='Cant Loose Them'
  elif (x['r_score']==1 and x['fm_score']==2):
    x['rfm_segment']='Hibernating'
  elif (x['r_score']==1 and x['fm_score']==1):
    x['rfm_segment']='Lost'
  return x

In [148]:
cust_seg4=cust_seg3.apply(func4,axis=1)

In [149]:
cust_seg4.head(30)

,CustomerID,Country,monetary,recency,frequency,m20,m40,m60,m80,m100,...,f20,f40,f60,f80,f100,r_score,m_score,f_score,fm_score,rfm_segment
0,12346.0,United Kingdom,77183.60,326,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,5,3,4.0,Cant Loose Them
1,12347.0,Iceland,4078.95,3,0.531646,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,5,5,2,4.0,Champions
2,12348.0,Finland,1437.24,76,0.383387,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,2,4,1,2.0,Customer Needing Attention
3,12349.0,Italy,1287.15,19,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,4,4,3,4.0,Loyal Customers
4,12350.0,Norway,294.40,311,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,2,3,2.0,Hibernating
5,12352.0,Norway,1147.44,37,0.724138,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,4,2,3.0,Potential Loyalists
6,12353.0,Bahrain,29.30,205,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,1,3,2.0,Hibernating
7,12354.0,Spain,925.95,233,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,4,3,4.0,Cant Loose Them
8,12355.0,Bahrain,414.00,215,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,2,3,2.0,Hibernating
9,12356.0,Portugal,1911.40,246,0.545455,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,5,2,4.0,Cant Loose Them
10,12357.0,Switzerland,5291.27,34,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,5,3,4.0,Loyal Customers
11,12358.0,Austria,908.16,2,0.335196,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,5,4,1,2.0,Potential Loyalists
12,12359.0,Cyprus,3642.33,58,0.394737,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,5,1,3.0,Potential Loyalists
13,12360.0,Austria,1914.26,53,0.505618,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,5,2,4.0,Loyal Customers
14,12361.0,Belgium,174.90,288,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,1,3,2.0,Hibernating
15,12362.0,Belgium,4377.28,4,0.931677,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,5,5,3,4.0,Champions
16,12363.0,Unspecified,552.00,110,0.368098,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,2,3,1,2.0,Customer Needing Attention
17,12364.0,Belgium,1186.20,8,0.888889,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,5,4,3,4.0,Champions
18,12365.0,Cyprus,307.94,292,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,2,3,2.0,Hibernating
19,12367.0,Denmark,150.90,5,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,5,1,3,2.0,Potential Loyalists
20,12370.0,Cyprus,3228.39,52,0.353982,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,5,1,3.0,Potential Loyalists
21,12370.0,Austria,3228.39,52,0.353982,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,5,1,3.0,Potential Loyalists
22,12371.0,Switzerland,1441.16,60,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,4,3,4.0,Loyal Customers
23,12372.0,Denmark,1196.04,72,0.352941,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,3,4,1,2.0,Customer Needing Attention
24,12373.0,Austria,324.60,312,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,2,3,2.0,Hibernating
25,12374.0,Austria,563.53,26,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,4,3,3,3.0,Potential Loyalists
26,12375.0,Finland,377.50,11,0.508475,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,5,2,2,2.0,Potential Loyalists
27,12377.0,Switzerland,1488.42,316,0.869565,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,1,4,3,4.0,Cant Loose Them
28,12378.0,Switzerland,3777.22,130,1.000000,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,2,5,3,4.0,At Risk
29,12379.0,Belgium,777.24,82,0.504202,218.344,428.914,845.726,1864.592,266194.22,...,0.461538,0.763775,1.0,1.0,32.903226,2,3,2,2.0,Customer Needing Attention